{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.app.name }}-{{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}
rules:
{{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.app.name }}-{{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.app.name }}-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
